services:
    chat-service:
        image: ghcr.io/ggml-org/llama.cpp:server-cuda
        container_name: chat-service

        environment:
            - HF_TOKEN=${HF_TOKEN}
            - HF_HOME=/models/.cache
            - OMP_NUM_THREADS=4

        volumes:
            - ~/.cache/llama-cpp:/models

        ports:
            - "8000:8000"

        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [ gpu ]

        command: >
            --hf-repo ggml-org/gemma-4-E4B-it-GGUF
            --hf-file gemma-4-E4B-it-Q4_K_M.gguf
            -c 8192
            -b 2048
            -ub 2048
            --tools all
            -ngl 99
            --port 8000
            --host 0.0.0.0

    embedding-service:
        image: vllm/vllm-openai
        container_name: embedding-service

        healthcheck:
            test: [ "CMD-SHELL", "curl -f http://localhost:8001/health || exit 1" ]
            interval: 10s
            timeout: 5s
            retries: 20
            start_period: 10s

        environment:
            - HF_TOKEN=${HF_TOKEN}

        volumes:
            - ~/.cache/huggingface:/root/.cache/huggingface
            - ./vllm_configs/dev-vllm-embedding.yml:/.config/vllm.yml

        ports:
            - "8001:8001"

        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [ gpu ]

        command: >
            --config /.config/vllm.yml

    reranker-service:
        image: vllm/vllm-openai
        container_name: reranker-service

        depends_on:
            embedding-service:
                condition: service_healthy

        environment:
            - HF_TOKEN=${HF_TOKEN}

        volumes:
            - ~/.cache/huggingface:/root/.cache/huggingface
            - ./vllm_configs/dev-vllm-reranker.yml:/.config/vllm.yml

        ports:
            - "8002:8002"

        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [ gpu ]

        command: >
            --config /.config/vllm.yml
