services:
    vllm-chat:
        image: vllm/vllm-openai
        container_name: vllm-chat

        environment:
            - HF_TOKEN=${HF_TOKEN}

        volumes:
            - ~/.cache/huggingface:/root/.cache/huggingface
            - ./vllm-configs/dev-vllm-chat.yml:/.config/vllm.yml

        ports:
            - "8000:8000"
        ipc: host

        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [gpu]
        
        command: >
            --config /.config/vllm.yml

    vllm-embedding:
        image: vllm/vllm-openai
        container_name: vllm-embedding

        environment:
            - HF_TOKEN=${HF_TOKEN}

        volumes:
            - ~/.cache/huggingface:/root/.cache/huggingface
            - ./vllm-configs/dev-vllm-embedding.yml:/.config/vllm.yml

        ports:
            - "8001:8001"
        ipc: host

        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [gpu]
        
        command: >
            --config /.config/vllm.yml

    vllm-reranker:
        image: vllm/vllm-openai
        container_name: vllm-reranker

        environment:
            - HF_TOKEN=${HF_TOKEN}

        volumes:
            - ~/.cache/huggingface:/root/.cache/huggingface
            - ./vllm-configs/dev-vllm-reranker.yml:/.config/vllm.yml

        ports:
            - "8002:8002"
        ipc: host

        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [gpu]
        
        command: >
            --config /.config/vllm.yml